name: Trigger MkDocs Build

on:
  pull_request_target:
    branches: [main]

jobs:
  call-build-docs:
    uses: Telucero/workflows/.github/workflows/check-mkdocs-build.yml@Central_repo_test
    with:
      repo_name: tanssi-docs
      mkdocs_repo: Telucero/tanssi-mkdocs
    secrets:
      REPO_SCOPED_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
